##########
# collectionbuilder-gh
##########

source-code: https://github.com/yunusugur/turkey-dh-atlas

##########
# SITE SETTINGS
title: Turkey DH Atlas
tagline: The DH Network (People, Institutions, Projects, and Publications) of Türkiye
description: "Digital Humanities Projects and People in Turkey and Turkish Studies"
author: Marmara University Center for DH

##########
# COLLECTION SETTINGS
metadata: dh_atlas_metadata

metadata-facets:
  - field: creator
    delimiter: ";"
  - field: calisma_ekibi
    delimiter: ";"
  - field: yontem
    delimiter: ";"
  - field: subjects
    delimiter: ";"
  - field: fonlayici
    delimiter: ";"
  - field: isbirligi
    delimiter: ";"

##########
# BUILD SETTINGS 
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
sass:
  style: compressed
